openapi: 3.0.3
info:
  title: Task Management API
  version: 1.0.0
  description: API for creating and retrieving tasks.
servers:
- url: https://api.example.com/v1
  description: Production server
paths:
  /tasks:
    get:
      tags:
      - Tasks
      summary: List all tasks
      description: Retrieve a list of all registered tasks.
      responses:
        '200':
          description: Task list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      tags:
      - Tasks
      summary: Create a task
      description: Add a new task.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /tasks/{id}:
    get:
      tags:
      - Tasks
      summary: Get task by ID
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The specified task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          example: '123'
        title:
          type: string
          example: Buy groceries
        completed:
          type: boolean
          example: false
      required:
      - title
    TaskCreate:
      type: object
      properties:
        title:
          type: string
          example: Buy groceries
        completed:
          type: boolean
          example: false
      required:
      - title
